# In _config.yml
title: LinkML Arrays
author: Jonny Saunders, Oliver Rübel, Chris Mungall, Ryan Ly
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - linkml-arrays-paper.bib